keys:
  - id: user-0
    port: 9005
    cipher: chacha20-ietf-poly1305
    secret: Secret0

  - id: user-1
    port: 9006
    cipher: chacha20-ietf-poly1305
    secret: Secret1

  - id: user-2
    port: 9007
    cipher: chacha20-ietf-poly1305
    secret: Secret2
